version: '3.8'
services:
  api:
    container_name: go-delivery-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    env_file:
      - .env
    command: npm run start:dev

  postgres:
    image: postgis/postgis:16-3.4
    container_name: go-delivery-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-prisma}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-topsecret}
      POSTGRES_DB: ${POSTGRES_DB:-godelivery}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: go-delivery-db
